---
name: Run Python Script

on:
  push:
    branches:
      - main  # Run on pushes to the 'main' branch

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2 '  # Choose your Python version

      - name: Run the script
        run: poetry run python pynenv/environment.py    # Replace with your script name
